# Generated by Django 6.0.3 on 2026-04-03 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='progress',
            field=models.IntegerField(choices=[(0, 'Активная'), (1, 'В процессе'), (2, 'Выполнена'), (3, 'Провалена'), (4, 'Отложена')], default=0, verbose_name='Прогресс'),
        ),
    ]
