# Generated by Django 6.0.3 on 2026-04-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_alter_task_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.TextField(choices=[('work', 'Работа'), ('home', 'Дом'), ('my_tasks', 'Мои задачи')], null=True, verbose_name='Теги'),
        ),
    ]
